DROP TABLE IF EXISTS users, items, bookings, comments, requests CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  description varchar(255) NOT NULL,
  requester_id bigint NOT NULL REFERENCES users (id),
  created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(255) NOT NULL,
  is_available boolean NOT NULL DEFAULT true,
  owner_id bigint NOT NULL REFERENCES users (id),
  request_id bigint REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  text varchar(255),
  item_id bigint NOT NULL REFERENCES items (id),
  author_id bigint NOT NULL REFERENCES users (id),
  created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  start_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id bigint NOT NULL REFERENCES items (id),
  booker_id bigint NOT NULL REFERENCES users (id),
  status varchar(255) NOT NULL
);